##############################################################################
#							PARAMETERS INPUT
##############################################################################
# Input data: insert the path to the data file and the parameters file

'Input' :

 'data' : 'path/to/velocities/data/file'

 'parameters' : 'path/to/parameters/file'

##############################################################################
# Choose whethere to cythonise the function module or not

'cythonise' : True

##############################################################################
# Select the Likelihood to adopt in the fitting.
# Choices: binned or unbinned Gaussian Likelihood

'Likelihood' : 'unbinned'

##############################################################################
# Select a dark matter density profile to adopt.
# Choices: Zhao, Burkert, Einasto

'DM_profile' :

 'profile'  : 'Zhao'

 'aDM' 	 :
  'value' : 1
  'free'  : False

 'bDM' 	 :
  'value' : 1
  'free'  : False

 'cDM' 	 :
  'value' : 3
  'free'  : True

 'alpha' :
  'value' : 0.17
  'free'  : False

##############################################################################
# Choose between either providing a generalised stellar distribution profile 
# (Hernquist 1990) or a surface brightness profile - choices: 
# Plummer (Plummer 1911), exponential, King (King 1965) or Sersic. 
# In the former (latter) case, the surface brightness (stellar velocity) 
# will be evalueuated via an inverse (direct) Abel transform.

'Hernquist' :

 'use' : True

 'rh'  :
  'valueue' : 1
  'free'  : True

 'aST' :
  'value' : 2
  'free'  : False

 'bST' :
  'value' : 5
  'free'  : False

 'cST' :
  'value' : 0
  'free'  : False

'surface_brightness' :

 'profile': 'Plummer'

  # Plummer profile
  # enter the half-light radius
  'rh' :
   'value' : 1
   'free'  : True

  # enter the exponential scale radius
  'rc' :
   'value' : 1
   'free'  : True

  # King profile
  # enter the core radius
  'rc' :
   'value' : 1
   'free'  : True
  # enter the maximum radius
  'rlim' :
   'value' : 2
   'free'  : False

  # Sersic profile
  # enter the scale radius
  'rc' :
   'value' : 1
   'free'  : True
  # enter the logarithmic decrease sharpness parameter
  'n' :
   'value' : 4
   'free'  : False

##############################################################################
# Select a velocity anisotropy profile.

# Isotropic velocity profile
'Anisotropy' :

 'profile' : 'IS'

 # Constant beta velocity profile
 # enter the anisotropy parameter beta
 'beta' :
  'value' : -1
  'free'  : True

 # Osipkov-Merritt profile (Osipkov 1979; Merritt 1985)
 # enter the scale radius
 'ra' :
  'value' : 1
  'free'  : True
